// This file is auto-generated by scripts/gen-i18n-keys.ts
// Do not edit manually. Run "npm run gen:i18n" to regenerate.

export type I18nKey =
  | 'analysis.analyzing'
  | 'analysis.analyzingCreative'
  | 'analysis.clarityScore'
  | 'analysis.complianceRisk'
  | 'analysis.ctas'
  | 'analysis.dailyLimitReached'
  | 'analysis.failed'
  | 'analysis.failedMessage'
  | 'analysis.fixes'
  | 'analysis.hookScore'
  | 'analysis.hooks'
  | 'analysis.issues'
  | 'analysis.overallScore'
  | 'analysis.readyToAnalyze'
  | 'analysis.retryAnalysis'
  | 'analysis.retrying'
  | 'analysis.script15s'
  | 'analysis.startAnalysis'
  | 'analysis.strengths'
  | 'analysis.summary'
  | 'analysis.title'
  | 'auth.alreadyHaveAccount'
  | 'auth.createAccount'
  | 'auth.creating'
  | 'auth.dontHaveAccount'
  | 'auth.emailNeverShared'
  | 'auth.invalidCredentials'
  | 'auth.login'
  | 'auth.loginFailed'
  | 'auth.passwordMinLength'
  | 'auth.pleaseFillAllFields'
  | 'auth.pleaseLoginAgain'
  | 'auth.pleaseRegister'
  | 'auth.pleaseRegisterAgain'
  | 'auth.registerNow'
  | 'auth.sessionExpired'
  | 'auth.signIn'
  | 'auth.signUp'
  | 'auth.signUpToGetStarted'
  | 'auth.signingIn'
  | 'auth.tokenNotFound'
  | 'auth.userExists'
  | 'auth.welcomeBack'
  | 'common.back'
  | 'common.cancel'
  | 'common.confirmPassword'
  | 'common.dashboard'
  | 'common.email'
  | 'common.empty'
  | 'common.error'
  | 'common.getStarted'
  | 'common.library'
  | 'common.loading'
  | 'common.logout'
  | 'common.noItems'
  | 'common.ok'
  | 'common.optional'
  | 'common.password'
  | 'common.refresh'
  | 'common.required'
  | 'common.reset'
  | 'common.retry'
  | 'common.save'
  | 'common.search'
  | 'common.settings'
  | 'common.upload'
  | 'common.viewAll'
  | 'creative.country'
  | 'creative.creativeCount'
  | 'creative.creativesCount'
  | 'creative.getStartedDescription'
  | 'creative.goal'
  | 'creative.language'
  | 'creative.metadata'
  | 'creative.noCreativesYet'
  | 'creative.noPreviewAvailable'
  | 'creative.notFound'
  | 'creative.notFoundDescription'
  | 'creative.platform'
  | 'creative.preview'
  | 'creative.recentCreatives'
  | 'creative.status.done'
  | 'creative.status.failed'
  | 'creative.status.processing'
  | 'creative.status.queued'
  | 'creative.untitled'
  | 'creative.vertical'
  | 'creative.videoNotSupported'
  | 'creative.yourLibrary'
  | 'dashboard.description'
  | 'dashboard.title'
  | 'dashboard.welcome'
  | 'dashboard.welcomeDescription'
  | 'errors.anErrorOccurred'
  | 'errors.checkLogs'
  | 'errors.failedToLoad'
  | 'errors.failedToLoadCreative'
  | 'errors.failedToLoadDashboard'
  | 'errors.failedToLoadImagePreview'
  | 'errors.failedToLoadLibrary'
  | 'errors.failedToLoadPreview'
  | 'errors.failedToLoadSettings'
  | 'errors.failedToLoadVideoPreview'
  | 'errors.fileNotFound'
  | 'errors.loginFailed'
  | 'errors.nonJsonResponse'
  | 'errors.notFound'
  | 'errors.registrationFailed'
  | 'errors.requestFailed'
  | 'errors.serverError'
  | 'errors.sessionExpired'
  | 'errors.unauthorized'
  | 'errors.uploadFailed'
  | 'library.description'
  | 'library.title'
  | 'nav.collections'
  | 'nav.dashboard'
  | 'nav.home'
  | 'nav.library'
  | 'nav.register'
  | 'nav.settings'
  | 'nav.upload'
  | 'settings.account'
  | 'settings.accountType'
  | 'settings.advancedAnalytics'
  | 'settings.analysesUsedToday'
  | 'settings.basicInsights'
  | 'settings.dailyAnalysisLimit'
  | 'settings.dangerZone'
  | 'settings.description'
  | 'settings.email'
  | 'settings.emailCannotChanged'
  | 'settings.free'
  | 'settings.freeTier'
  | 'settings.freeTierIncludes'
  | 'settings.imageVideoUploads'
  | 'settings.limits'
  | 'settings.of'
  | 'settings.profile'
  | 'settings.signOut'
  | 'settings.signOutButton'
  | 'settings.signOutDescription'
  | 'settings.title'
  | 'settings.upTo3Analyses'
  | 'settings.userId'
  | 'upload.analysisFailed'
  | 'upload.analysisLimitReached'
  | 'upload.analyzing'
  | 'upload.chooseFile'
  | 'upload.country'
  | 'upload.countryPlaceholder'
  | 'upload.done'
  | 'upload.file'
  | 'upload.getStarted'
  | 'upload.goal'
  | 'upload.goalPlaceholder'
  | 'upload.language'
  | 'upload.languagePlaceholder'
  | 'upload.platform'
  | 'upload.platformPlaceholder'
  | 'upload.pleaseSelectFile'
  | 'upload.processing'
  | 'upload.processingCreative'
  | 'upload.title'
  | 'upload.uploadFailed'
  | 'upload.uploadSucceededNoId'
  | 'upload.uploading'
  | 'upload.vertical'
  | 'upload.verticalPlaceholder';

export const i18nKeys: readonly I18nKey[] = [
  'analysis.analyzing',
  'analysis.analyzingCreative',
  'analysis.clarityScore',
  'analysis.complianceRisk',
  'analysis.ctas',
  'analysis.dailyLimitReached',
  'analysis.failed',
  'analysis.failedMessage',
  'analysis.fixes',
  'analysis.hookScore',
  'analysis.hooks',
  'analysis.issues',
  'analysis.overallScore',
  'analysis.readyToAnalyze',
  'analysis.retryAnalysis',
  'analysis.retrying',
  'analysis.script15s',
  'analysis.startAnalysis',
  'analysis.strengths',
  'analysis.summary',
  'analysis.title',
  'auth.alreadyHaveAccount',
  'auth.createAccount',
  'auth.creating',
  'auth.dontHaveAccount',
  'auth.emailNeverShared',
  'auth.invalidCredentials',
  'auth.login',
  'auth.loginFailed',
  'auth.passwordMinLength',
  'auth.pleaseFillAllFields',
  'auth.pleaseLoginAgain',
  'auth.pleaseRegister',
  'auth.pleaseRegisterAgain',
  'auth.registerNow',
  'auth.sessionExpired',
  'auth.signIn',
  'auth.signUp',
  'auth.signUpToGetStarted',
  'auth.signingIn',
  'auth.tokenNotFound',
  'auth.userExists',
  'auth.welcomeBack',
  'common.back',
  'common.cancel',
  'common.confirmPassword',
  'common.dashboard',
  'common.email',
  'common.empty',
  'common.error',
  'common.getStarted',
  'common.library',
  'common.loading',
  'common.logout',
  'common.noItems',
  'common.ok',
  'common.optional',
  'common.password',
  'common.refresh',
  'common.required',
  'common.reset',
  'common.retry',
  'common.save',
  'common.search',
  'common.settings',
  'common.upload',
  'common.viewAll',
  'creative.country',
  'creative.creativeCount',
  'creative.creativesCount',
  'creative.getStartedDescription',
  'creative.goal',
  'creative.language',
  'creative.metadata',
  'creative.noCreativesYet',
  'creative.noPreviewAvailable',
  'creative.notFound',
  'creative.notFoundDescription',
  'creative.platform',
  'creative.preview',
  'creative.recentCreatives',
  'creative.status.done',
  'creative.status.failed',
  'creative.status.processing',
  'creative.status.queued',
  'creative.untitled',
  'creative.vertical',
  'creative.videoNotSupported',
  'creative.yourLibrary',
  'dashboard.description',
  'dashboard.title',
  'dashboard.welcome',
  'dashboard.welcomeDescription',
  'errors.anErrorOccurred',
  'errors.checkLogs',
  'errors.failedToLoad',
  'errors.failedToLoadCreative',
  'errors.failedToLoadDashboard',
  'errors.failedToLoadImagePreview',
  'errors.failedToLoadLibrary',
  'errors.failedToLoadPreview',
  'errors.failedToLoadSettings',
  'errors.failedToLoadVideoPreview',
  'errors.fileNotFound',
  'errors.loginFailed',
  'errors.nonJsonResponse',
  'errors.notFound',
  'errors.registrationFailed',
  'errors.requestFailed',
  'errors.serverError',
  'errors.sessionExpired',
  'errors.unauthorized',
  'errors.uploadFailed',
  'library.description',
  'library.title',
  'nav.collections',
  'nav.dashboard',
  'nav.home',
  'nav.library',
  'nav.register',
  'nav.settings',
  'nav.upload',
  'settings.account',
  'settings.accountType',
  'settings.advancedAnalytics',
  'settings.analysesUsedToday',
  'settings.basicInsights',
  'settings.dailyAnalysisLimit',
  'settings.dangerZone',
  'settings.description',
  'settings.email',
  'settings.emailCannotChanged',
  'settings.free',
  'settings.freeTier',
  'settings.freeTierIncludes',
  'settings.imageVideoUploads',
  'settings.limits',
  'settings.of',
  'settings.profile',
  'settings.signOut',
  'settings.signOutButton',
  'settings.signOutDescription',
  'settings.title',
  'settings.upTo3Analyses',
  'settings.userId',
  'upload.analysisFailed',
  'upload.analysisLimitReached',
  'upload.analyzing',
  'upload.chooseFile',
  'upload.country',
  'upload.countryPlaceholder',
  'upload.done',
  'upload.file',
  'upload.getStarted',
  'upload.goal',
  'upload.goalPlaceholder',
  'upload.language',
  'upload.languagePlaceholder',
  'upload.platform',
  'upload.platformPlaceholder',
  'upload.pleaseSelectFile',
  'upload.processing',
  'upload.processingCreative',
  'upload.title',
  'upload.uploadFailed',
  'upload.uploadSucceededNoId',
  'upload.uploading',
  'upload.vertical',
  'upload.verticalPlaceholder'
] as const;
