#!/usr/bin/env node

/**
 * Script to generate TypeScript types from i18n JSON files
 * Reads lib/i18n/messages/en.json and generates lib/i18n/keys.ts
 */

import * as fs from 'fs';
import * as path from 'path';

const enJsonPath = path.join(__dirname, '../lib/i18n/messages/en.json');
const keysTsPath = path.join(__dirname, '../lib/i18n/keys.ts');

interface Messages {
  [key: string]: string | Messages;
}

function flattenKeys(obj: Messages, prefix = ''): string[] {
  const keys: string[] = [];
  
  for (const [key, value] of Object.entries(obj)) {
    const fullKey = prefix ? `${prefix}.${key}` : key;
    
    if (typeof value === 'string') {
      keys.push(fullKey);
    } else if (typeof value === 'object' && value !== null) {
      keys.push(...flattenKeys(value, fullKey));
    }
  }
  
  return keys;
}

function generateTypeScriptKeys(keys: string[]): string {
  const sortedKeys = keys.sort();
  
  const unionType = sortedKeys.map(key => `  | '${key}'`).join('\n');
  
  return `// This file is auto-generated by scripts/gen-i18n-keys.ts
// Do not edit manually. Run "npm run gen:i18n" to regenerate.

export type I18nKey =
${unionType};

export const i18nKeys: readonly I18nKey[] = [
${sortedKeys.map(key => `  '${key}'`).join(',\n')}
] as const;
`;
}

// Read en.json
const enJsonContent = fs.readFileSync(enJsonPath, 'utf-8');
const enMessages: Messages = JSON.parse(enJsonContent);

// Flatten keys
const keys = flattenKeys(enMessages);

// Generate TypeScript file
const tsContent = generateTypeScriptKeys(keys);

// Write to keys.ts
fs.writeFileSync(keysTsPath, tsContent, 'utf-8');

console.log(`✅ Generated ${keys.length} i18n keys in ${keysTsPath}`);
